# Source and destination folder
source      : ./.tmp/source
destination : ./.tmp/public_html_temp

# Site info
title       : Reboot lanyon
description : "Demo site for Reboot lanyon theme"
tagline     : "Learner"
baseurl     : "/reboot-lanyon"
url         : https://sonapraneeth-a.github.io
favicon     :
lang        : en-us
version     : 1.0.6 # Please use semantic versioning (semver.org)
repository  : sonapraneeth-a.github.io/reboot-lanyon
environment : "production"
build       : "gulp"

# SEO
logo:
social:
    name: Sona Praneeth Akula
    links:
        - https://twitter.com/sonapraneeth_a
        - https://www.facebook.com/sonapraneeth.akula/
        - https://www.linkedin.com/in/sona-praneeth-akula
        - https://github.com/sonapraneeth-a
twitter:
    username: sonapraneeth_a

# Site settings
plugins_dir  : _plugins
layouts_dir  : _layouts
data_dir     : _data
includes_dir : _includes
posts_dir    : _posts
plugins:
    - jekyll-paginate-v2
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-last-modified-at
#    - mm-jekyll-prism
    - jemoji
    - jekyll-seo-tag
    - jekyll-typogrify
    - jekyll/figure
    - jekyll-gist
    - html-proofer
markdown: kramdown
kramdown:
    auto_ids      : true
    entity_output : as_char
    toc_levels    : 1..4
    smart_quotes  : lsquo,rsquo,ldquo,rdquo
    input         : GFM
    hard_wrap     : false
    footnote_nr   : 1
    show_warnings : true
# sass:
#     style         : compressed
#     sass_dir      : _scss
highlighter       : rouge
timezone          : Asia/Kolkata
encoding          : "utf-8"
markdown_ext      : "markdown,mkdown,mkdn,mkd,md"

post:
    related         : true
    comments        : true
    sharing         : true
    comments_plugin : disqus
words_per_minute    : 180

permalink           : '/blog/:year/:month/:day/:title/'

pagination:
    enabled      : true
    collection   : 'posts'
    per_page     : 5
    title        : ':title | Page :num of :max'
    permalink    : '/:num/'
    sort_field   : 'date'
    sort_reverse : true
    trail:
        before : 1
        after  : 2


autopages:
  enabled: false

# Old Jekyl paginate plugin
# paginate: 5
# paginate_path: '/blog/:num'
# permalink: '/blog/:year/:month/:day/:title/'

future      : false
show_drafts : false

collections:
    projects:
        output: true

# Author info
author:
    name: Sona Praneeth Akula
    description:
    gravatar: 250c61d0435096d44102ab5fcd590d9c # md5 hash of your email address
    contact:
        linkedin : https://www.linkedin.com/in/sona-praneeth-akula
        github   : https://github.com/sonapraneeth-a
        facebook : https://www.facebook.com/sonapraneeth.akula
        twitter  : https://twitter.com/sonapraneeth_a
        email    : mailto:praneethakulasona@gmail.com
    usernames:
        linkedin : sona-praneeth-akula
        github   : sonapraneeth-a
        facebook : akula.sonapraneeth
        twitter  : sonapraneeth_a
        email    : praneethakulasona@gmail.com


# Navigation Menu
menu:
    - title : 'Home'
      url   : '/'
      icon  : 'home'
      class : 'home'
    - title : 'Projects'
      url   : '/projects/'
      icon  : 'file-code'
      class : 'project'
      sublinks:
        - title : 'Categories'
          url   : '/projects/categories/'
          icon  : 'folder-open'
          class : 'categories'
        - title : 'Search'
          url   : '/projects/search/'
          icon  : 'search'
          class : 'search'
        - title : 'Tags'
          url   : '/projects/tags/'
          icon  : 'tag'
          class : 'tags'
        - title : 'Archives'
          url   : '/projects/archives/'
          icon  : 'file-archive'
          class : 'archives'
    - title : 'Blog'
      url   : '/blog/'
      icon  : 'pencil-alt'
      class : 'blog'
      sublinks:
        - title : 'Categories'
          url   : '/blog/categories/'
          icon  : 'folder-open'
          class : 'categories'
        - title : 'Search'
          url   : '/blog/search/'
          icon  : 'search'
          class : 'search'
        - title : 'Tags'
          url   : '/blog/tags/'
          icon  : 'tag'
          class : 'tags'
        - title : 'Archives'
          url   : '/blog/archives/'
          icon  : 'file-archive'
          class : 'archives'

google_analytics_token : 'UA-90733014-1' # leave blank if you don't want google analytics
disqus_short_name      : 'sonapraneethakula' # leave blank if you don't want disqus
staticman:
    branch             : "reboot-lanyon"

webmaster_verifications:
    google: -RmPuAcL0rqC5SPAGz0s2KbMQETk08-zni-fkB2aQuQ
    bing: 
    alexa: 
    yandex: 
    baidu: 

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - Gemfile
    - Gemfile.lock
include:
    - .htaccess

compress_html:
    clippings  : []
    comments   : ["<!-- ", " -->"]
    endings    : []
    ignore:
        envs: []
    blanklines : true
    profile    : false
    startings  : []
