# Source and destination folder
source      : source
destination : public_html

# Site info
title       : Reboot lanyon
description : "Demo site for Reboot lanyon theme"
tagline     : "Learner"
baseurl     : ""
url         : https://sonapraneeth-a.github.io
favicon     :
lang        : en-us
version     : 2.0.0-alpha.1 # Please use semantic versioning (semver.org)
repository  : sonapraneeth-a.github.io/reboot-lanyon
environment : "development"
build       : "jekyll"

# Site config
flat        : true
skin        : base-01

# SEO
logo:
social:
    name: Sona Praneeth Akula
    links:
    - https://twitter.com/sonapraneeth_a
    - https://www.facebook.com/sonapraneeth.akula/
    - https://www.linkedin.com/in/sona-praneeth-akula
    - https://github.com/sonapraneeth-a
twitter:
    username: sonapraneeth_a

# Site settings
collections_dir : _collections
plugins_dir     : _plugins
layouts_dir     : _layouts
data_dir        : _data
includes_dir    : _includes
posts_dir       : _posts
plugins:
    - jekyll-paginate-v2
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-last-modified-at
    - mm-jekyll-prism
    - jemoji
    - jekyll-seo-tag
    - jekyll-typogrify
    - jekyll-figure
    - jekyll-gist
    - pygments
    - jekyll-tidy
    #- html-proofer
markdown: kramdown
kramdown:
    auto_ids           : true
    entity_output      : as_char
    toc_levels         : 1..4
    smart_quotes       : lsquo,rsquo,ldquo,rdquo
    input              : GFM
    hard_wrap          : false
    footnote_nr        : 1
    show_warnings      : true
    syntax_highlighter : rouge
sass:
    style         : compressed
    sass_dir      : _sass
highlighter       : rouge
timezone          : Asia/Kolkata
encoding          : "utf-8"
markdown_ext      : "markdown,mkdown,mkdn,mkd,md"

post:
    related         : true
    comments        : true
    sharing         : true
    comments_plugin : disqus
words_per_minute    : 180

permalink           : '/blog/:year/:month/:day/:title/'

pagination:
    enabled      : true
    collection   : 'posts'
    per_page     : 5
    title        : ':title | Page :num of :max'
    permalink    : '/:num/'
    sort_field   : 'date'
    sort_reverse : true
    trail:
        before : 1
        after  : 2


autopages:
    enabled: false

# Old Jekyl paginate plugin
# paginate: 5
# paginate_path: '/blog/:num'
# permalink: '/blog/:year/:month/:day/:title/'

future      : true
show_drafts : true
incremental : true


collections:
    pages:
        output: true
        permalink: /:slug
    posts:
        output: true
        permalink: /blog/:year/:month/:day/:title/
    projects:
        output: true
        permalink: /:collection/:path/

# Author info
author:
    name: Sona Praneeth Akula
    description:
    gravatar: 250c61d0435096d44102ab5fcd590d9c # md5 hash of your email address
    contact:
        linkedin : https://www.linkedin.com/in/sona-praneeth-akula
        github   : https://github.com/sonapraneeth-a
        facebook : https://www.facebook.com/sonapraneeth.akula
        twitter  : https://twitter.com/sonapraneeth_a
        email    : mailto:praneethakulasona@gmail.com
    usernames:
        linkedin : sona-praneeth-akula
        github   : sonapraneeth-a
        facebook : akula.sonapraneeth
        twitter  : sonapraneeth_a
        email    : praneethakulasona@gmail.com


# Navigation Menu
menu:
    - title : 'Home'
      url   : '/'
      icon  : 'home'
      class : 'home'
    - title : 'Projects'
      url   : '/projects/'
      icon  : 'file-code'
      class : 'project'
      sublinks:
          - title : 'Categories'
            url   : '/projects/categories/'
            icon  : 'folder-open'
            class : 'categories'
          - title : 'Search'
            url   : '/projects/search/'
            icon  : 'search'
            class : 'search'
          - title : 'Tags'
            url   : '/projects/tags/'
            icon  : 'tag'
            class : 'tags'
          - title : 'Archives'
            url   : '/projects/archives/'
            icon  : 'file-archive'
            class : 'archives'
    - title : 'Blog'
      url   : '/blog/'
      icon  : 'pencil-alt'
      class : 'blog'
      sublinks:
          - title : 'Categories'
            url   : '/blog/categories/'
            icon  : 'folder-open'
            class : 'categories'
          - title : 'Search'
            url   : '/blog/search/'
            icon  : 'search'
            class : 'search'
          - title : 'Tags'
            url   : '/blog/tags/'
            icon  : 'tag'
            class : 'tags'
          - title : 'Archives'
            url   : '/blog/archives/'
            icon  : 'file-archive'
            class : 'archives'

google_analytics_token : 'UA-90733014-1' # leave blank if you don't want google analytics
disqus_short_name      : 'sonapraneethakula' # leave blank if you don't want disqus
staticman:
    branch             : "reboot-lanyon"

webmaster_verifications:
    google: -RmPuAcL0rqC5SPAGz0s2KbMQETk08-zni-fkB2aQuQ
    bing:
    alexa:
    yandex:
    baidu:

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - TODO.md
    - REFERENCES.md
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json
include:
    - .htaccess
    - _collections

jekyll_tidy:
    exclude: [""]
    ignore_env:
    compress_html: false


# Defaults
defaults:
    # _posts
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          read_time: true
          share: true
          related: true
    # _algorithms
    - scope:
          path: "_algorithms"
          type: algorithms
      values:
          layout: collection
          author_profile: true
          share: true
          publish: true
          comments: true
          related: true
    # _pages
    - scope:
          path: "_pages"
          type: pages
      values:
          layout: default
          author_profile: true

#compress_html:
#    clippings  : []
#    comments   : [""]
#    endings    : []
#    ignore:
#        envs: [local]
#    blanklines : true
#    profile    : false
#    startings  : []
