# Source and destination folder
source      : ./.tmp/source
destination : ./.tmp/public_html_temp

# Environment info
environment : "development"
build       : "gulp"

# URLs
## Actual URL of the website
url         :
## Sub URL from where site is loaded
baseurl     :
