# Source and destination folder
source      : source
destination : public_html

# Site info
title       : Reboot lanyon
description : "Demo site for Reboot lanyon theme"
tagline     : "Learner"
baseurl     : ""
url         : https://sonapraneeth-a.github.io
favicon     :
lang        : en-us
version     : 2.1.0 # Please use semantic versioning (semver.org)
repository  : sonapraneeth-a.github.io/reboot-lanyon
environment : "development"
build       : "jekyll"

# Site config
flat        : true
skin        : base-01
sidebar:
    display  : push # push, overlay
    position : left # Currently set it from _base-01.scss
progress_bar:
    color    : red
    progress : aqua
    show     : false

# SEO
logo:
social:
    name: Sona Praneeth Akula
    links:
        - https://twitter.com/sonapraneeth_a
        - https://www.facebook.com/sonapraneeth.akula/
        - https://www.linkedin.com/in/sona-praneeth-akula
        - https://github.com/sonapraneeth-a
twitter:
    username: sonapraneeth_a

# Site settings
collections_dir : _collections
plugins_dir     : _plugins
layouts_dir     : _layouts
data_dir        : _data
includes_dir    : _includes
posts_dir       : _posts
plugins:
    - jekyll-paginate-v2
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-last-modified-at
    - mm-jekyll-prism
    - jemoji
    - jekyll-seo-tag
    - jekyll-typogrify
    - jekyll-figure
    - jekyll-gist
    - pygments
    - jekyll-tidy
    #- html-proofer
markdown: kramdown
kramdown:
    auto_ids           : true
    entity_output      : as_char
    toc_levels         : 1..4
    smart_quotes       : lsquo,rsquo,ldquo,rdquo
    input              : GFM
    hard_wrap          : false
    footnote_nr        : 1
    show_warnings      : true
    syntax_highlighter : rouge
sass:
    style         : compressed
    sass_dir      : _sass
highlighter       : rouge
timezone          : Asia/Kolkata
encoding          : "utf-8"
markdown_ext      : "markdown,mkdown,mkdn,mkd,md"

post:
    related         : true
    comments        : true
    sharing         : true
    comments_plugin : disqus
words_per_minute    : 180

permalink           : "/blog/:year/:month/:day/:title/"

#autopages:
#    enabled: true
#    tags:
#        enabled: false
#    categories:
#        enabled: false
#    collections:
#        enabled: true
#        layouts:
#            - "autopage_collection.html"
#        title: ":coll" # :coll is replaced by the collection name
#        permalink: "/:coll/"
#        slugify:
#            mode: "pretty"
#            cased: true

pagination:
    enabled      : true
    collection   : "posts"
    per_page     : 2
    title        : ":title | Page :num of :max"
    permalink    : "/:num/"
    sort_field   : "date"
    sort_reverse : true
    trail:
        before : 2
        after  : 2

autopages:
    enabled: false

# Old Jekyl paginate plugin
# paginate: 5
# paginate_path: "/blog/:num"
# permalink: "/blog/:year/:month/:day/:title/"

future      : true
show_drafts : true
incremental : true

collections:
    index-pages:
        output: true
        permalink: /:slug/
    posts:
        output: true
        permalink: /blog/:year/:month/:day/:title/
    projects:
        output: true
        permalink: /:collection/:path/
    seasons:
        output: true
        label: Seasons
        permalink: /collections/:collection/:path/
    planets:
        output: true
        label: Planets
        permalink: /collections/:collection/:path/

google_analytics_token : "UA-90733014-1" # leave blank if you don't want google analytics
disqus_short_name      : "sonapraneethakula" # leave blank if you don't want disqus
staticman:
    branch             : "reboot-lanyon"

webmaster_verifications:
    google: -RmPuAcL0rqC5SPAGz0s2KbMQETk08-zni-fkB2aQuQ
    bing:
    alexa:
    yandex:
    baidu:

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - TODO.md
    - REFERENCES.md
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json
include:
    - .htaccess
    - _collections

jekyll_tidy:
    exclude: [""]
    ignore_env:
    compress_html: false


# Defaults
defaults:
    # _posts
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          excerpt_separator: <!--more-->
          author_profile: true
          read_time: true
          sharing: true
          publish: false
          related: true
          comments: true
          toc: true
          toc_label: Table of Contents
          toc_icon: table
    # _seasons
    - scope:
          path: "_seasons"
          type: seasons
      values:
          layout: collection
          excerpt_separator: <!--more-->
          author_profile: true
          read_time: true
          sharing: true
          publish: false
          related: true
          comments: true
          toc: true
          toc_label: Table of Contents
          toc_icon: table
    # _planets
    - scope:
          path: "_planets"
          type: planets
      values:
          layout: collection
          excerpt_separator: <!--more-->
          author_profile: true
          read_time: true
          sharing: true
          publish: false
          related: true
          comments: true
          toc: true
          toc_label: Table of Contents
          toc_icon: table
    # _index-pages
    - scope:
          path: "_index-pages"
          type: pages
      values:
          layout: default
          excerpt_separator: <!--more-->
          author_profile: true
          read_time: true
          sharing: true
          publish: false
          related: true
          comments: true
          toc: true
          toc_label: Table of Contents
          toc_icon: table

#compress_html:
#    clippings  : []
#    comments   : [""]
#    endings    : []
#    ignore:
#        envs: [local]
#    blanklines : true
#    profile    : false
#    startings  : []
