## Actual URL of the website
url         : https://v2-reboot-lanyon-netlify.netlify.com
## Sub URL from where site is loaded
baseurl     : /

environment : "production"
build       : "netlify"

pagination:
    per_page     : 5
